---
title: "Research"
output: html_document
---

<br>

## Publications

1.	**Lin, X.**, Chau, C., Ma, K. et al. DCATS: differential composition analysis for flexible single-cell experimental designs. *Genome Biol* 24, 151 (2023). https://doi.org/10.1186/s13059-023-02980-3
2.	Miao, Z., **Lin, X.**, Li, J., Ho, J., Meng, Q., & Zhang, X. (2025). scRecover: Discriminating True and False Zeros in Single-Cell RNA-Seq Data for Imputation. Statistics in medicine, 44(5), e10334. (co-first author)
3.	Meng, Q., Wei, L., Ma, K., Shi, M., Lin, X., Ho, J. W., ... & Zhang, X. (2024). scDecouple: decoupling cellular response from infected proportion bias in scCRISPR-seq. *Briefings in Bioinformatics*, 25(2), bbae011.
4.	Warin, J., Vedrenne, N., Tam, V., Zhu, M., Yin, D., Lin, X., ... & Camus, A. (2024). In vitro and in vivo models define a molecular signature reference for human embryonic notochordal cells. *Iscience*, 27(2).
5.	Xue, Y., Su, Z., Lin, X., Ho, M. K., & Yu, K. H. (2024). Single-cell lineage tracing with endogenous markers. *Biophysical Reviews*, 1-15.
6.	**X. Lin**, G. Deng, Y. Li, J. Ge, J.W.K. Ho, Y. Liu, GeneRAG: Enhancing Large Language Models with Gene-Related Task by Retrieval-Augmented Generation, bioRxiv (2024). https://www.biorxiv.org/content/10.1101/2024.06.24.600176v1 

  <br>
 
## Talks

1. Contributed Talks in BioC Asia 2021: [Link](https://biocasia2021.bioconductor.org/contributions/) [Video](https://www.youtube.com/watch?v=_Fh3sp59ui0) [Slides](https://f1000research.com/slides/10-1119)

 <br>
 
## Awards

1. [Silver presentation award](./support_files/silver_award.pdf) in NSFC/RPG Workshop on Single-Cell Data Science.

2. [Bau Tsu Zung Bau Kwan Yeu Hing Research and Clinical Fellowship](https://scholar.aas.hku.hk/?action=showonesscheme&ss_id=471&backb=1)

 <br>
 
## Tutorial Materials for Workshops

1. Introduction to R(Chapter 5): [Link](https://holab-hku.github.io/R-workshop/)

2. Fundamentals of scRNASeq Analysis: [Link](https://holab-hku.github.io//Fundamental-scRNA/)

 <br>

## Project

### Group Project

1. Factors Associated with Mental Health in Tech Companies: [Link](https://runanon.github.io/final.github.io/) 

 * My responsibility: Models Building

2. Using Newton-Raphson and Logistic-LASSO for Predicting Breast Cancer Status: [Report](./support_files/Optimization_project.pdf)
[Code](https://github.com/thecbp/P8160_optimization_project)

 * My responsibility: Newton-Raphson Algorithm

3. Glasses' Type Prediction: [Report](./Glass_type_prediction.pdf)
[Code](https://github.com/runanon/p8106_final)

 * My responsibility: Support Vector Machine

4. Houses' Prices Prediction: [Report](./support_files/House_price_prediction.pdf)
[Code](https://github.com/runanon/P8106_MIDTERM_PROJECT)

 * My responsibility: Data Preprocessing and Writing Report
 
 <br>

### Personal Project

1. Hurricane Trajectory Prediction: [Questions](./support_files/hurricane_questions.pdf)
[Report](./support_files/hurricane_report.pdf)
[Code](https://github.com/linxy29/P8160_final_project)

2. 基于贝叶斯算法的等位基因特异的m6A鉴定算法开发: [Bachelor Dissertation](./support_files/毕业论文.pdf)


